version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    target-branch: 'dev'
    commit-message:
      prefix: 'chore(deps):'
    reviewers:
      - 'dex2dot0'
    assignees:
      - 'dex2dot0'
    labels:
      - 'dependencies'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every week
      interval: 'weekly'
