version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-minor']
      # sst will be updated with SST CLI which also sets CDK version
      - dependency-name: 'sst'
      - dependency-name: 'aws-cdk-lib'
    open-pull-requests-limit: 10
    target-branch: 'dev'
    commit-message:
      prefix: 'chore(deps):'
    reviewers:
      - 'dex2dot0'
    assignees:
      - 'dex2dot0'
    labels:
      - 'dependencies'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every week
      interval: 'weekly'
